# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    remember-me:
      key: 62227d4d159c4e6f364fe22307707385fd773e55
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterNoI18nSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
